title = "D&G"
baseURL = "https://diceandgames.com/"
languageCode = "en-us"
theme = "ananke"


DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Weird War and Retropunk"
  facebook = "https://www.facebook.com/gaming/dustbattles/"
  twitter = ""
  instagram = "https://www.instagram.com/dustbattles/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  body_classes = "avenir bg-white"
  post_content_classes = "avenir bg-white"
  recent_posts_number = 4
